export enum TypeormConfigurationEnvironmentVariablesEnum {
  TYPEORM_CONFIGURATION__DATABASE_TYPE = 'TYPEORM_CONFIGURATION__DATABASE_TYPE',
  TYPEORM_CONFIGURATION__DATABASE_FILEPATH = 'TYPEORM_CONFIGURATION__DATABASE_FILEPATH',
  TYPEORM_CONFIGURATION__SYNCHRONIZE = 'TYPEORM_CONFIGURATION__SYNCHRONIZE',
}
